server:
  port: ${PORT:8081}

spring:
  application:
    name: tour-service
  datasource:
    url: jdbc:mysql://tours.cnmkzpeyddof.eu-central-1.rds.amazonaws.com:3304/tours?autoReconnect=true&useSSL=false
    username: toursroot
    password: root1111


eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${EUREKA_CLIENT_SERVICE_URL_HOSTNAME:localhost}:${EUREKA_CLIENT_SERVICE_URL_PORT:8761}/eureka/